name: ui_squircle
description: A Flutter package for smooth squircle shapes, borders, and decorations.
version: 0.0.1
homepage: https://github.com/kenji-07/ui_squircle

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.2.0